language: rust
sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

rust:
  - nightly
  # - beta
  # - stable

before_script:
  - |
      if [ "${TRAVIS_OS_NAME}" = 'osx' ]; then
        export PATH=$HOME/Library/Python/2.7/bin:$PATH
        export KCOV=""
      else
        export PATH=$HOME/.local/bin:$PATH
        export KCOV="${TRAVIS_BUILD_DIR}/kcov/build/src/kcov --exclude-pattern=/.cargo --coveralls-id=${TRAVIS_JOB_ID} ${TRAVIS_BUILD_DIR}/coverage"
      fi
  - |
      # FIXME: travis-ci/travis-ci#4011
      # Caching feature never works on osx, so we download only ten problems.
      if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        ONLY_TOP10=1 ./etc/download_puzzles.sh
      else
        ./etc/download_puzzles.sh
      fi
  - |
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget https://github.com/SimonKagstrom/kcov/archive/master.zip
        unzip master.zip
        mv kcov-master kcov
        mkdir kcov/build
        cd kcov/build
        cmake ..
        make
        cd ${TRAVIS_BUILD_DIR}
      fi

script:
  # srither-core package
  - cargo build -p srither-core
  - cargo test --no-run -p srither-core
  - ${KCOV} ./target/debug/deps/srither_core-*
  - cargo bench -p srither-core

  # srither-solver package
  - cargo build -p srither-solver
  - cargo test --no-run -p srither-solver
  - ${KCOV} ./target/debug/deps/srither_solver-*
  - cargo bench -p srither-solver

  # srither package
  # build
  - cargo build
  - cargo build --release
  # test and collect coverage
  - cargo test --no-run
  - ${KCOV} ./target/debug/srither-*
  - ${KCOV} ./target/debug/srither solve ./puzzle/example.txt
  - ${KCOV} ./target/debug/srither solve --all ./puzzle/empty_2x1.txt
  - ${KCOV} ./target/debug/srither solve --all ./puzzle/empty_2x2.txt
  - find ./puzzle -type f -name "*.txt" | xargs ${KCOV} ./target/debug/srither test
  - ${KCOV} ./target/debug/srither bench ./puzzle/example.txt
  # benchmark
  - cargo bench
  - find ./puzzle -type f -name "*.txt" | xargs ./target/release/srither bench --only-hardest 5
  # generate doc
  - cargo doc

after_success:
  - |
      [ ${TRAVIS_RUST_VERSION} = nightly ] &&
      [ ${TRAVIS_BRANCH} = master ] &&
      [ ${TRAVIS_PULL_REQUEST} = false ] &&
      echo "<meta http-equiv=refresh content=0;url=srither/index.html>" > target/doc/index.html &&
      pip install 'ghp-import' --user &&
      ghp-import -n target/doc &&
      git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages

cache:
  directories:
    - puzzle/janko
    - puzzle/java
    - puzzle/nikoli

os:
  - linux
  - osx
