language: rust
sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

rust:
  - nightly
  # - beta
  # - stable

before_script:
  - pip install 'travis-cargo<0.2' --user
  - |
      if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        export PATH=$HOME/Library/Python/2.7/bin:$PATH
      else
        export PATH=$HOME/.local/bin:$PATH
      fi
  - |
      # FIXME: travis-ci/travis-ci#4011
      # Caching feature never works on osx, so we download only ten problems.
      if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        ONLY_TOP10=1 ./etc/download_puzzles.sh
      else
        ./etc/download_puzzles.sh
      fi

script:
  - cd "${TRAVIS_BUILD_DIR}/core"
  - travis-cargo build
  - travis-cargo test
  - travis-cargo bench
  - cd "${TRAVIS_BUILD_DIR}/solver"
  - travis-cargo build
  - travis-cargo test
  - travis-cargo bench
  - cd "${TRAVIS_BUILD_DIR}/cli"
  - travis-cargo build -- --release
  # FIXME: huonw/travis-cargo#22
  # - cannot pass arguments to slsr-cli
  # - travis-cargo run -- --release -- solve --all ../puzzle/empty_2x1.txt
  # - travis-cargo run -- --release -- solve --all ../puzzle/empty_2x2.txt
  - ./target/release/slsr-cli solve ../puzzle/example.txt
  - ./target/release/slsr-cli solve --all ../puzzle/empty_2x1.txt
  - ./target/release/slsr-cli solve --all ../puzzle/empty_2x2.txt
  - travis-cargo test
  # FIXME: huonw/travis-cargo#22
  - find ../puzzle -type f -name "*.txt" | xargs ./target/release/slsr-cli test
  - travis-cargo bench
  # FIXME: huonw/travis-cargo#22
  - find ../puzzle -type f -name "*.txt" | xargs ./target/release/slsr-cli bench --only-hardest 10
  - travis-cargo --only ${DOC_UPLOAD_VERSION} doc

after_success:
  - cd "${TRAVIS_BUILD_DIR}/cli"
  - travis-cargo --only ${DOC_UPLOAD_VERSION} doc-upload
  - travis-cargo coveralls --no-sudo

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - DOC_UPLOAD_VERSION=nightly
    - DOC_UPLOAD_PKG=cli

cache:
  directories:
    - puzzle/janko
    - puzzle/java

os:
  - linux
  - osx

