language: rust
sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

rust:
  - nightly
  # - beta
  # - stable

before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH

script:
  - cd "${TRAVIS_BUILD_DIR}/${PKGDIR}"
  - travis-cargo build -- --release
  - |
      if [ "${PKGDIR}" = "cli" ]; then
        travis-cargo run -- --release ../puzzle/example.txt
        # FIXME: huonw/travis-cargo#22
        # cannot pass arguments to slsr-cli
        # travis-cargo run -- --release -- --all ../puzzle/empty_2x1.txt
        # travis-cargo run -- --release -- --all ../puzzle/empty_2x2.txt
      fi
  - travis-cargo test
  - travis-cargo bench
  - |
      if [ "${PKGDIR}" = "${DOC_UPLOAD_PKG}" ]; then
        travis-cargo --only ${DOC_UPLOAD_VERSION} doc
      fi

after_success:
  - |
      if [ "${PKGDIR}" = "${DOC_UPLOAD_PKG}" ]; then
        travis-cargo --only ${DOC_UPLOAD_VERSION} doc-upload
      fi
  - travis-cargo coveralls --no-sudo

env:
  matrix:
    - PKGDIR=cli
    - PKGDIR=core
    - PKGDIR=solver
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - DOC_UPLOAD_VERSION=nightly
    - DOC_UPLOAD_PKG=cli
