language: rust
sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

rust:
  - nightly
  # - beta
  # - stable

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build -- --release &&
      travis-cargo run < puzzle/example.txt &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only ${DOC_UPLOAD_VERSION} doc

after_success:
  - travis-cargo --only ${DOC_UPLOAD_VERSION} doc-upload
  - travis-cargo coveralls --no-sudo

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - DOC_UPLOAD_VERSION=nightly
