language: rust
sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

rust:
  - nightly
  # - beta
  # - stable

before_script:
  - |
      if [ "${TRAVIS_OS_NAME}" = 'osx' ]; then
        export PATH=$HOME/Library/Python/2.7/bin:$PATH
        export KCOV=""
      else
        export PATH=$HOME/.local/bin:$PATH
        export KCOV="${TRAVIS_BUILD_DIR}/kcov/build/src/kcov --exclude-pattern=/.cargo --coveralls-id=${TRAVIS_JOB_ID} ${TRAVIS_BUILD_DIR}/coverage"
      fi
  - |
      # FIXME: travis-ci/travis-ci#4011
      # Caching feature never works on osx, so we download only ten problems.
      if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        ONLY_TOP10=1 ./etc/download_puzzles.sh
      else
        ./etc/download_puzzles.sh
      fi
  - |
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget https://github.com/SimonKagstrom/kcov/archive/master.zip
        unzip master.zip
        mv kcov-master kcov
        mkdir kcov/build
        cd kcov/build
        cmake ..
        make
      fi

script:
  # core package
  - cd "${TRAVIS_BUILD_DIR}/srither-core"
  - cargo build
  - cargo test --no-run
  - ${KCOV} ./target/debug/srither_core-*
  - cargo bench

  # solver package
  - cd "${TRAVIS_BUILD_DIR}/srither-solver"
  - cargo build
  - cargo test --no-run
  - ${KCOV} ./target/debug/srither_solver-*
  - cargo bench

  # cli package
  # build
  - cd "${TRAVIS_BUILD_DIR}/srither-cli"
  - cargo build
  - cargo build --release
  # test and collect coverage
  - cargo test --no-run
  - ${KCOV} ./target/debug/srither_cli-*
  - ${KCOV} ./target/debug/srither-cli solve ../puzzle/example.txt
  - ${KCOV} ./target/debug/srither-cli solve --all ../puzzle/empty_2x1.txt
  - ${KCOV} ./target/debug/srither-cli solve --all ../puzzle/empty_2x2.txt
  - find ../puzzle -type f -name "*.txt" | xargs ${KCOV} ./target/debug/srither-cli test
  - ${KCOV} ./target/debug/srither-cli bench ../puzzle/example.txt
  # benchmark
  - cargo bench
  - find ../puzzle -type f -name "*.txt" | xargs ./target/release/srither-cli bench --only-hardest 10
  # generate doc
  - cargo doc

after_success:
  - cd "${TRAVIS_BUILD_DIR}/cli"
  - |
      [ ${TRAVIS_RUST_VERSION} = nightly ] &&
      [ ${TRAVIS_BRANCH} = master ] &&
      [ ${TRAVIS_PULL_REQUEST} = false ] &&
      echo "<meta http-equiv=refresh content=0;url=srither_cli/index.html>" > target/doc/index.html &&
      pip install 'ghp-import' --user &&
      ghp-import -n target/doc &&
      git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages

cache:
  directories:
    - puzzle/janko
    - puzzle/java

os:
  - linux
  - osx
