environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  # core package
  - cd %APPVEYOR_BUILD_FOLDER%\srither-core
  - cargo build
  - cargo test
  - cargo bench

  # solver package
  - cd %APPVEYOR_BUILD_FOLDER%\srither-solver
  - cargo build
  - cargo test
  - cargo bench

  # cli package
  - cd %APPVEYOR_BUILD_FOLDER%\srither-cli
  - cargo build
  - cargo run -- solve ..\puzzle\example.txt
  - cargo run -- solve --all ..\puzzle\empty_2x1.txt
  - cargo run -- solve --all ..\puzzle\empty_2x2.txt
  - cargo test
  - cargo bench
