environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: i686-pc-windows-gnu
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\core
  - cargo build
  - cargo test
  - cargo bench
  - cd %APPVEYOR_BUILD_FOLDER%\solver
  - cargo build
  - cargo test
  - cd %APPVEYOR_BUILD_FOLDER%\cli
  - cargo build --release
  - cargo run --release -- solve ..\puzzle\example.txt
  - cargo run --release -- solve --all ..\puzzle\empty_2x1.txt
  - cargo run --release -- solve --all ..\puzzle\empty_2x2.txt
  - cargo test
  - cargo bench
