(function() {var implementors = {};
implementors['board_game_geom'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;<a class='struct' href='board_game_geom/struct.Move.html' title='board_game_geom::Move'>Move</a>&gt; for <a class='struct' href='board_game_geom/struct.Point.html' title='board_game_geom::Point'>Point</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;<a class='struct' href='board_game_geom/struct.Move.html' title='board_game_geom::Move'>Move</a>&gt; for <a class='struct' href='board_game_geom/struct.Move.html' title='board_game_geom::Move'>Move</a>",];implementors['srither_core'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;<a class='struct' href='srither_core/geom/struct.Move.html' title='srither_core::geom::Move'>Move</a>&gt; for <a class='struct' href='srither_core/geom/struct.Point.html' title='srither_core::geom::Point'>Point</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;<a class='struct' href='srither_core/geom/struct.Move.html' title='srither_core::geom::Move'>Move</a>&gt; for <a class='struct' href='srither_core/geom/struct.Move.html' title='srither_core::geom::Move'>Move</a>",];implementors['libc'] = [];implementors['time'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a> for <a class='struct' href='time/struct.Duration.html' title='time::Duration'>Duration</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;<a class='struct' href='time/struct.Duration.html' title='time::Duration'>Duration</a>&gt; for <a class='struct' href='time/struct.Timespec.html' title='time::Timespec'>Timespec</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;<a class='struct' href='time/struct.Duration.html' title='time::Duration'>Duration</a>&gt; for <a class='struct' href='time/struct.SteadyTime.html' title='time::SteadyTime'>SteadyTime</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;<a class='struct' href='time/struct.Duration.html' title='time::Duration'>Duration</a>&gt; for <a class='struct' href='time/struct.Tm.html' title='time::Tm'>Tm</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
