(function() {var implementors = {};
implementors['board_game_geom'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Mul.html' title='core::ops::Mul'>Mul</a>&lt;<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.i32.html'>i32</a>&gt; for <a class='struct' href='board_game_geom/struct.Move.html' title='board_game_geom::Move'>Move</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Mul.html' title='core::ops::Mul'>Mul</a>&lt;<a class='struct' href='board_game_geom/struct.Rotation.html' title='board_game_geom::Rotation'>Rotation</a>&gt; for <a class='struct' href='board_game_geom/struct.Rotation.html' title='board_game_geom::Rotation'>Rotation</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Mul.html' title='core::ops::Mul'>Mul</a>&lt;<a class='struct' href='board_game_geom/struct.Move.html' title='board_game_geom::Move'>Move</a>&gt; for <a class='struct' href='board_game_geom/struct.Rotation.html' title='board_game_geom::Rotation'>Rotation</a>",];implementors['srither_core'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Mul.html' title='core::ops::Mul'>Mul</a>&lt;<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.i32.html'>i32</a>&gt; for <a class='struct' href='srither_core/geom/struct.Move.html' title='srither_core::geom::Move'>Move</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Mul.html' title='core::ops::Mul'>Mul</a>&lt;<a class='struct' href='srither_core/geom/struct.Rotation.html' title='srither_core::geom::Rotation'>Rotation</a>&gt; for <a class='struct' href='srither_core/geom/struct.Rotation.html' title='srither_core::geom::Rotation'>Rotation</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Mul.html' title='core::ops::Mul'>Mul</a>&lt;<a class='struct' href='srither_core/geom/struct.Move.html' title='srither_core::geom::Move'>Move</a>&gt; for <a class='struct' href='srither_core/geom/struct.Rotation.html' title='srither_core::geom::Rotation'>Rotation</a>",];implementors['libc'] = [];implementors['time'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Mul.html' title='core::ops::Mul'>Mul</a>&lt;<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.i32.html'>i32</a>&gt; for <a class='struct' href='time/struct.Duration.html' title='time::Duration'>Duration</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
